import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'ta' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {

  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.upload': 'Detect Disease',
    'nav.about': 'About',
    'nav.admin': 'Admin',
    
    // Homepage
    'hero.title': 'Detect Crop Disease Instantly with AI',
    'hero.subtitle': 'Help your crops stay healthy with instant disease detection using your phone camera',
    'hero.cta': 'Get Started',
    'features.title': 'Why Choose AgroGuardian?',
    'features.offline': 'Works Offline',
    'features.offline.desc': 'No internet? No problem. Works without connection.',
    'features.multilingual': 'Multiple Languages',
    'features.multilingual.desc': 'Available in Hindi, Tamil, Bengali and English.',
    'features.instant': 'Instant Results',
    'features.instant.desc': 'Get disease detection and remedies in seconds.',
    
    // Upload Page
    'upload.title': 'Upload Crop Image',
    'upload.subtitle': 'Take a photo or upload an image of your crop for AI analysis',
    'upload.crop.label': 'Select Crop Type',
    'upload.crop.placeholder': 'Choose your crop...',
    'upload.drop.text': 'Drop image here or click to upload',
    'upload.drop.formats': 'Supports: JPG, PNG (Max 5MB)',
    'upload.camera': 'Take Photo',
    'upload.gallery': 'Choose from Gallery',
    'upload.detect': 'Detect Disease',
    'upload.processing': 'Analyzing image...',
    'upload.error.invalidImage': 'Please select a valid image file',
    
    // Results
    'result.title': 'Detection Results',
    'result.crop': 'Crop',
    'result.disease': 'Detected Issue',
    'result.confidence': 'Confidence',
    'result.remedy.title': 'Recommended Treatment',
    'result.remedy.steps': 'Treatment Steps',
    'result.preventive': 'Preventive Measures',
    'result.share': 'Share Report',
    'result.share.whatsapp': 'Share on WhatsApp',
    'result.download': 'Download Report',
    'result.scan.again': 'Scan Another Crop',
    'chat.ask.assistant': 'Ask AI Assistant',
    'chat.placeholder': 'Type your farming question...',
    'chat.voice.start': 'Start voice input',
    'chat.voice.stop': 'Stop voice input',
    'chat.speak': 'Read aloud',
    'chat.stop.speaking': 'Stop reading',
    
    // About
    'about.title': 'About AgroGuardian',
    'about.mission': 'Our Mission',
    'about.mission.text': 'Empowering farmers with AI-powered crop disease detection to improve agricultural productivity and food security.',
    'about.team': 'Our Team',
    'about.contact': 'Contact Us',
    'about.contact.form': 'Send us a message',
    'about.contact.name': 'Name',
    'about.contact.email': 'Email',
    'about.contact.message': 'Message',
    'about.contact.send': 'Send Message',
    
    // Admin
    'admin.title': 'Admin Dashboard',
    'admin.total.scans': 'Total Scans',
    'admin.diseases.detected': 'Diseases Detected',
    'admin.users.active': 'Active Users',
    'admin.accuracy': 'Detection Accuracy',
    'admin.recent.cases': 'Recent Cases',
    'admin.export': 'Export Data',
    'admin.crop': 'Crop',
    'admin.disease': 'Disease',
    'admin.date': 'Date',
    'admin.language': 'Language',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Something went wrong',
    'common.retry': 'Try Again',
    'common.success': 'Success!',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.close': 'Close',
    
    // Crops
    'crops.tomato': 'Tomato',
    'crops.potato': 'Potato',
    'crops.wheat': 'Wheat',
    'crops.rice': 'Rice',
    'crops.corn': 'Corn',
    'crops.cotton': 'Cotton',
    'crops.sugarcane': 'Sugarcane',
    'crops.soybean': 'Soybean',
    
    // Footer
    'footer.brand': 'AgroIndia',
    'footer.description': 'Empowering farmers with AI-powered crop disease detection for sustainable agriculture.',
    'footer.quicklinks': 'Quick Links',
    'footer.dashboard': 'Dashboard',
    'footer.heatmap': 'Heatmap',
    'footer.copyright': '© 2024 AgroIndia. All rights reserved.',

    // HomePage
    'home.hero.smartFarming': 'Smart Farming',
    'home.hero.subtitle': 'Revolutionizing agriculture with AI-powered crop disease detection for a sustainable future',
    'home.hero.cta': 'Predict Now',
    'home.how.title': 'How It Works',
    'home.how.subtitle': 'Get crop disease diagnosis in three simple steps',
    'home.steps.upload.title': 'Upload',
    'home.steps.upload.desc': 'Take a photo of your crop leaf using your smartphone camera',
    'home.steps.diagnose.title': 'Diagnose',
    'home.steps.diagnose.desc': 'Our AI analyzes the image and identifies potential diseases',
    'home.steps.remedies.title': 'Get Remedies',
    'home.steps.remedies.desc': 'Receive detailed treatment recommendations and prevention tips',
    'home.sustainability.title': 'Why Sustainable?',
    'home.sustainability.subtitle': 'Building a greener future through smart agriculture technology',
    'home.sustainability.soil.title': 'Soil Health',
    'home.sustainability.soil.desc': 'Enhance soil fertility through organic practices and maintain microbial diversity for long-term productivity',
    'home.sustainability.cost.title': 'Cost Efficiency',
    'home.sustainability.cost.desc': 'Reduce input costs by 40% through targeted treatments and prevention strategies that save money',
    'home.sustainability.yield.title': 'Future Yields',
    'home.sustainability.yield.desc': 'Increase crop yields by 25% with data-driven insights that optimize growth conditions sustainably',
    'home.stats.accuracy': 'Accuracy Rate',
    'home.stats.diseases': 'Diseases Detected',
    'home.stats.farmers': 'Farmers Helped',
    'home.stats.support': 'Support Available',
    'home.cta.title': 'Ready to Transform Your Farming?',
    'home.cta.subtitle': 'Join thousands of farmers using AgroIndia for sustainable crop management and disease prevention.',
    'home.cta.button': 'Start Your Journey',
    // ResultPage
    'result.error.noResults': 'No results found',
    'result.error.uploadNew': 'Upload New Image',
    'result.backToUpload': 'Back to Upload',
    'result.title': 'Detection Results',
    'result.reference.healthy': 'Healthy',
    'result.reference.early': 'Early Stage',
    'result.reference.moderate': 'Moderate',
    'result.reference.severe': 'Severe',
    'result.reference.guide': 'Disease Progression Guide',
    'result.reference.desc': 'These reference photos show the progression of the disease from healthy to severe stages. Use them to identify symptoms and understand the severity level.',
    'result.prevention.title': 'Future Prevention Tips',
    'result.share': 'Share Results',
    'result.download': 'Download Report',
    'result.askAssistant': 'Ask AI Assistant',
    'result.scanAgain': 'Scan Another Crop',
  },
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.upload': 'रोग की जांच',
    'nav.about': 'हमारे बारे में',
    'nav.admin': 'एडमिन',
    
    // Homepage
    'hero.title': 'AI के साथ तुरंत फसल रोग का पता लगाएं',
    'hero.subtitle': 'अपने फोन कैमरा से तुरंत रोग का पता लगाकर अपनी फसलों को स्वस्थ रखने में मदद करें',
    'hero.cta': 'शुरू करें',
    'features.title': 'AgroGuardian क्यों चुनें?',
    'features.offline': 'ऑफलाइन काम करता है',
    'features.offline.desc': 'इंटरनेट नहीं? कोई समस्या नहीं। बिना कनेक्शन के काम करता है।',
    'features.multilingual': 'कई भाषाएं',
    'features.multilingual.desc': 'हिंदी, तमिल, बंगाली और अंग्रेजी में उपलब्ध।',
    'features.instant': 'तुरंत परिणाम',
    'features.instant.desc': 'सेकंडों में रोग का पता लगाने और उपचार पाएं।',
    
    // Upload Page
    'upload.title': 'फसल की तस्वीर अपलोड करें',
    'upload.subtitle': 'AI विश्लेषण के लिए अपनी फसल की तस्वीर लें या अपलोड करें',
    'upload.crop.label': 'फसल का प्रकार चुनें',
    'upload.crop.placeholder': 'अपनी फसल चुनें...',
    'upload.drop.text': 'यहां तस्वीर छोड़ें या अपलोड करने के लिए क्लिक करें',
    'upload.drop.formats': 'समर्थित: JPG, PNG (अधिकतम 5MB)',
    'upload.camera': 'फोटो लें',
    'upload.gallery': 'गैलरी से चुनें',
    'upload.detect': 'रोग का पता लगाएं',
    'upload.processing': 'तस्वीर का विश्लेषण...',
    'upload.error.invalidImage': 'कृपया एक वैध छवि चुनें',
    
    // Results
    'result.title': 'जांच परिणाम',
    'result.crop': 'फसल',
    'result.disease': 'पहचाना गया मुद्दा',
    'result.confidence': 'विश्वास',
    'result.remedy.title': 'अनुशंसित उपचार',
    'result.remedy.steps': 'उपचार के चरण',
    'result.preventive': 'निवारक उपाय',
    'result.share': 'रिपोर्ट साझा करें',
    'result.share.whatsapp': 'WhatsApp पर साझा करें',
    'result.download': 'रिपोर्ट डाउनलोड करें',
    'result.scan.again': 'दूसरी फसल स्कैन करें',
    'chat.ask.assistant': 'AI सहायक से पूछें',
    'chat.placeholder': 'अपना कृषि प्रश्न लिखें...',
    'chat.voice.start': 'आवाज़ इनपुट शुरू करें',
    'chat.voice.stop': 'आवाज़ इनपुट बंद करें',
    'chat.speak': 'जोर से पढ़ें',
    'chat.stop.speaking': 'पढ़ना बंद करें',
    
    // About
    'about.title': 'AgroGuardian के बारे में',
    'about.mission': 'हमारा मिशन',
    'about.mission.text': 'कृषि उत्पादकता और खाद्य सुरक्षा में सुधार के लिए AI-संचालित फसल रोग का पता लगाने के साथ किसानों को सशक्त बनाना।',
    'about.team': 'हमारी टीम',
    'about.contact': 'संपर्क करें',
    'about.contact.form': 'हमें संदेश भेजें',
    'about.contact.name': 'नाम',
    'about.contact.email': 'ईमेल',
    'about.contact.message': 'संदेश',
    'about.contact.send': 'संदेश भेजें',
    
    // Admin
    'admin.title': 'Admin Dashboard',
    'admin.total.scans': 'Total Scans',
    'admin.diseases.detected': 'Diseases Detected',
    'admin.users.active': 'Active Users',
    'admin.accuracy': 'Detection Accuracy',
    'admin.recent.cases': 'Recent Cases',
    'admin.export': 'Export Data',
    'admin.crop': 'Crop',
    'admin.disease': 'Disease',
    'admin.date': 'Date',
    'admin.language': 'Language',
    
    // Crops
    'crops.tomato': 'टमाटर',
    'crops.potato': 'आलू',
    'crops.wheat': 'गेहूं',
    'crops.rice': 'चावल',
    'crops.corn': 'मक्का',
    'crops.cotton': 'कपास',
    'crops.sugarcane': 'गन्ना',
    'crops.soybean': 'सोयाबीन',
    
    // Footer
    'footer.brand': 'एग्रोइंडिया',
    'footer.description': 'किसानों को AI-संचालित फसल रोग पहचान के साथ सतत कृषि के लिए सशक्त बनाना।',
    'footer.quicklinks': 'त्वरित लिंक',
    'footer.dashboard': 'डैशबोर्ड',
    'footer.heatmap': 'हीटमैप',
    'footer.copyright': '© 2024 एग्रोइंडिया. सर्वाधिकार सुरक्षित।',

    // HomePage
    'home.hero.smartFarming': 'स्मार्ट खेती',
    'home.hero.subtitle': 'AI-संचालित फसल रोग पहचान के साथ कृषि में क्रांति, टिकाऊ भविष्य के लिए',
    'home.hero.cta': 'अब भविष्यवाणी करें',
    'home.how.title': 'कैसे काम करता है',
    'home.how.subtitle': 'तीन आसान चरणों में फसल रोग का निदान प्राप्त करें',
    'home.steps.upload.title': 'अपलोड करें',
    'home.steps.upload.desc': 'अपने स्मार्टफोन कैमरे से अपनी फसल की पत्ती की फोटो लें',
    'home.steps.diagnose.title': 'निदान',
    'home.steps.diagnose.desc': 'हमारा AI छवि का विश्लेषण करता है और संभावित रोगों की पहचान करता है',
    'home.steps.remedies.title': 'उपचार प्राप्त करें',
    'home.steps.remedies.desc': 'विस्तृत उपचार सिफारिशें और रोकथाम के सुझाव प्राप्त करें',
    'home.sustainability.title': 'क्यों टिकाऊ?',
    'home.sustainability.subtitle': 'स्मार्ट कृषि तकनीक के माध्यम से हरित भविष्य का निर्माण',
    'home.sustainability.soil.title': 'मिट्टी की सेहत',
    'home.sustainability.soil.desc': 'जैविक तरीकों से मिट्टी की उर्वरता बढ़ाएं और दीर्घकालिक उत्पादकता के लिए सूक्ष्मजीव विविधता बनाए रखें',
    'home.sustainability.cost.title': 'लागत दक्षता',
    'home.sustainability.cost.desc': 'लक्षित उपचार और रोकथाम रणनीतियों के माध्यम से लागत में 40% तक की बचत करें',
    'home.sustainability.yield.title': 'भविष्य की पैदावार',
    'home.sustainability.yield.desc': 'डेटा-आधारित सुझावों से फसल की पैदावार 25% तक बढ़ाएं',
    'home.stats.accuracy': 'सटीकता दर',
    'home.stats.diseases': 'पता लगाए गए रोग',
    'home.stats.farmers': 'किसानों की मदद की',
    'home.stats.support': 'सहायता उपलब्ध',
    'home.cta.title': 'क्या आप अपनी खेती बदलने के लिए तैयार हैं?',
    'home.cta.subtitle': 'AgroIndia के साथ हजारों किसान टिकाऊ फसल प्रबंधन और रोग रोकथाम के लिए जुड़ रहे हैं।',
    'home.cta.button': 'अपनी यात्रा शुरू करें',
    // ResultPage
    'result.error.noResults': 'कोई परिणाम नहीं मिला',
    'result.error.uploadNew': 'नई छवि अपलोड करें',
    'result.backToUpload': 'अपलोड पर वापस जाएं',
    'result.title': 'जांच परिणाम',
    'result.reference.healthy': 'स्वस्थ',
    'result.reference.early': 'प्रारंभिक चरण',
    'result.reference.moderate': 'मध्यम',
    'result.reference.severe': 'गंभीर',
    'result.reference.guide': 'रोग प्रगति गाइड',
    'result.reference.desc': 'ये संदर्भ चित्र रोग की प्रगति को स्वस्थ से गंभीर चरण तक दिखाते हैं। लक्षणों की पहचान और गंभीरता समझने के लिए इनका उपयोग करें।',
    'result.prevention.title': 'भविष्य की रोकथाम के सुझाव',
    'result.share': 'परिणाम साझा करें',
    'result.download': 'रिपोर्ट डाउनलोड करें',
    'result.askAssistant': 'AI सहायक से पूछें',
    'result.scanAgain': 'एक और फसल स्कैन करें',
  },
  ta: {
    // Navigation
    'nav.home': 'முகப்பு',
    'nav.upload': 'நோய் கண்டறிதல்',
    'nav.about': 'எங்களைப் பற்றி',
    'nav.admin': 'நிர்வாகி',
    
    // Homepage
    'hero.title': 'AI உடன் உடனடியாக பயிர் நோயைக் கண்டறியுங்கள்',
    'hero.subtitle': 'உங்கள் ஃபோன் கேமராவைப் பயன்படுத்தி உடனடி நோய் கண்டறிதலுடன் உங்கள் பயிர்களை ஆரோக்கியமாக வைத்திருக்க உதவுங்கள்',
    'hero.cta': 'தொடங்குங்கள்',
    'features.title': 'Why Choose AgroGuardian?',
    'features.offline': 'Works Offline',
    'features.offline.desc': 'No internet? No problem. Works without connection.',
    'features.multilingual': 'Multiple Languages',
    'features.multilingual.desc': 'Available in Hindi, Tamil, Bengali and English.',
    'features.instant': 'Instant Results',
    'features.instant.desc': 'Get disease detection and remedies in seconds.',
    
    // Upload Page  
    'upload.title': 'பயிர் படத்தைப் பதிவேற்றவும்',
    'upload.subtitle': 'Take a photo or upload an image of your crop for AI analysis',
    'upload.crop.label': 'பயிர் வகையைத் தேர்ந்தெடுக்கவும்',
    'upload.crop.placeholder': 'உங்கள் பயிரைத் தேர்ந்தெடுக்கவும்...',
    'upload.drop.text': 'Drop image here or click to upload',
    'upload.drop.formats': 'Supports: JPG, PNG (Max 5MB)',
    'upload.camera': 'Take Photo',
    'upload.gallery': 'Choose from Gallery',
    'upload.detect': 'நோயைக் கண்டறியுங்கள்',
    'upload.processing': 'Analyzing image...',
    'upload.error.invalidImage': 'கோரிக்கையில் ஒரு சரியான படம் தேர்ந்தெடுக்கவும்',
    
    // Results
    'result.title': 'Detection Results',
    'result.crop': 'Crop',
    'result.disease': 'Detected Issue',
    'result.confidence': 'Confidence',
    'result.remedy.title': 'Recommended Treatment',
    'result.remedy.steps': 'Treatment Steps',
    'result.preventive': 'Preventive Measures',
    'result.share': 'Share Report',
    'result.share.whatsapp': 'Share on WhatsApp',
    'result.download': 'Download Report',
    'result.scan.again': 'Scan Another Crop',
    'chat.ask.assistant': 'Ask AI Assistant',
    'chat.placeholder': 'Type your farming question...',
    'chat.voice.start': 'Start voice input',
    'chat.voice.stop': 'Stop voice input',
    'chat.speak': 'Read aloud',
    'chat.stop.speaking': 'Stop reading',
    
    // About
    'about.title': 'AgroGuardian பற்றி',
    'about.mission': 'Our Mission',
    'about.mission.text': 'Empowering farmers with AI-powered crop disease detection to improve agricultural productivity and food security.',
    'about.team': 'Our Team',
    'about.contact': 'Contact Us',
    'about.contact.form': 'Send us a message',
    'about.contact.name': 'Name',
    'about.contact.email': 'Email',
    'about.contact.message': 'Message',
    'about.contact.send': 'Send Message',
    
    // Admin
    'admin.title': 'Admin Dashboard',
    'admin.total.scans': 'Total Scans',
    'admin.diseases.detected': 'Diseases Detected',
    'admin.users.active': 'Active Users',
    'admin.accuracy': 'Detection Accuracy',
    'admin.recent.cases': 'Recent Cases',
    'admin.export': 'Export Data',
    'admin.crop': 'Crop',
    'admin.disease': 'Disease',
    'admin.date': 'Date',
    'admin.language': 'Language',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Something went wrong',
    'common.retry': 'Try Again',
    'common.success': 'Success!',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.close': 'Close',
    
    // Crops
    'crops.tomato': 'தக்காளி',
    'crops.potato': 'உருளைக்கிழங்கு',
    'crops.wheat': 'கோதுமை',
    'crops.rice': 'அரிசி',
    'crops.corn': 'சோளம்',
    'crops.cotton': 'பருத்தி',
    'crops.sugarcane': 'கரும்பு',
    'crops.soybean': 'சோயாபீன்',
    
    // Footer
    'footer.brand': 'அக்ரோஇந்தியா',
    'footer.description': 'AI-யால் இயக்கப்படும் பயிர் நோய் கண்டறிதலுடன் விவசாயிகளை நிலையான வேளாண்மைக்கு அதிகாரப்படுத்துதல்.',
    'footer.quicklinks': 'விரைவு இணைப்புகள்',
    'footer.dashboard': 'டாஷ்போர்டு',
    'footer.heatmap': 'வெப்பநிலை வரைபடம்',
    'footer.copyright': '© 2024 அக்ரோஇந்தியா. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',

    // HomePage
    'home.hero.smartFarming': 'ஸ்மார்ட் விவசாயம்',
    'home.hero.subtitle': 'AI மூலம் இயக்கப்படும் பயிர் நோய் கண்டறிதலுடன் விவசாயத்தில் புரட்சி, நிலையான எதிர்காலத்திற்கு',
    'home.hero.cta': 'இப்போது கணிக்கவும்',
    'home.how.title': 'எப்படி வேலை செய்கிறது',
    'home.how.subtitle': 'மூன்று எளிய படிகளில் பயிர் நோய் கண்டறிதலைப் பெறுங்கள்',
    'home.steps.upload.title': 'பதிவேற்றவும்',
    'home.steps.upload.desc': 'உங்கள் ஸ்மார்ட்போன் கேமராவைப் பயன்படுத்தி பயிர் இலை புகைப்படத்தை எடுக்கவும்',
    'home.steps.diagnose.title': 'நோயறிதல்',
    'home.steps.diagnose.desc': 'எங்கள் AI படத்தை பகுப்பாய்வு செய்து நோய்களை கண்டறிகிறது',
    'home.steps.remedies.title': 'சிகிச்சை பெறுங்கள்',
    'home.steps.remedies.desc': 'விரிவான சிகிச்சைரிந்துரைகள் மற்றும் தடுப்பு குறிப்புகளைப் பெறுங்கள்',
    'home.sustainability.title': 'ஏன் நிலையானது?',
    'home.sustainability.subtitle': 'ஸ்மார்ட் விவசாய தொழில்நுட்பம் மூலம் பசுமை எதிர்காலம்',
    'home.sustainability.soil.title': 'மண் ஆரோக்கியம்',
    'home.sustainability.soil.desc': 'நிலையான விளைவிற்காக உயிரணு பல்வகைமையை பராமரித்து, காரிக முறைகள் மூலம் மண் வளத்தை மேம்படுத்துங்கள்',
    'home.sustainability.cost.title': 'செலவு திறன்',
    'home.sustainability.cost.desc': 'இலக்கு வைத்த சிகிச்சைகள் மற்றும் தடுப்பு மூலம் செலவுகளை 40% குறைக்கவும்',
    'home.sustainability.yield.title': 'எதிர்கால விளைச்சல்',
    'home.sustainability.yield.desc': 'தரவு சார்ந்த அறிவுரைகளுடன் பயிர் விளைச்சலை 25% அதிகரிக்கவும்',
    'home.stats.accuracy': 'துல்லிய விகிதம்',
    'home.stats.diseases': 'கண்டறியப்பட்ட நோய்கள்',
    'home.stats.farmers': 'உதவிய விவசாயிகள்',
    'home.stats.support': 'ஆதரவு கிடைக்கும்',
    'home.cta.title': 'உங்கள் விவசாயத்தை மாற்ற தயாரா?',
    'home.cta.subtitle': 'AgroIndia-வை பயன்படுத்தும் ஆயிரக்கணக்கான விவசாயிகளுடன் சேருங்கள்.',
    'home.cta.button': 'உங்கள் பயணத்தைத் தொடங்குங்கள்',
    // ResultPage
    'result.error.noResults': 'முடிவுகள் இல்லை',
    'result.error.uploadNew': 'புதிய படத்தை பதிவேற்றவும்',
    'result.backToUpload': 'பதிவேற்றத்திற்கு திரும்பவும்',
    'result.title': 'கண்டறிதல் முடிவுகள்',
    'result.reference.healthy': 'ஆரோக்கியம்',
    'result.reference.early': 'ஆரம்ப நிலை',
    'result.reference.moderate': 'மிதமான',
    'result.reference.severe': 'கடுமையான',
    'result.reference.guide': 'நோய் முன்னேற்ற வழிகாட்டி',
    'result.reference.desc': 'இந்த குறிப்பு படங்கள் நோயின் முன்னேற்றத்தை ஆரோக்கியத்திலிருந்து கடுமையான நிலை வரை காட்டுகின்றன. அறிகுறிகளை அடையாளம் காணவும், கடுமையைப் புரிந்துகொள்ளவும் பயன்படுத்தவும்.',
    'result.prevention.title': 'எதிர்கால தடுப்பு குறிப்புகள்',
    'result.share': 'முடிவுகளை பகிரவும்',
    'result.download': 'அறிக்கை பதிவிறக்கவும்',
    'result.askAssistant': 'AI உதவியாளரை கேளுங்கள்',
    'result.scanAgain': 'மற்றொரு பயிரை ஸ்கேன் செய்யவும்',
  },
  bn: {
    // Navigation
    'nav.home': 'হোম',
    'nav.upload': 'রোগ নির্ণয়',
    'nav.about': 'আমাদের সম্পর্কে',
    'nav.admin': 'অ্যাডমিন',
    
    // Homepage
    'hero.title': 'AI দিয়ে তাৎক্ষণিক ফসলের রোগ নির্ণয় করুন',
    'hero.subtitle': 'আপনার ফোন ক্যামেরা ব্যবহার করে তাৎক্ষণিক রোগ নির্ণয়ের মাধ্যমে আপনার ফসল সুস্থ রাখতে সাহায্য করুন',
    'hero.cta': 'শুরু করুন',
    'features.title': 'Why Choose AgroGuardian?',
    'features.offline': 'Works Offline',
    'features.offline.desc': 'No internet? No problem. Works without connection.',
    'features.multilingual': 'Multiple Languages',
    'features.multilingual.desc': 'Available in Hindi, Tamil, Bengali and English.',
    'features.instant': 'Instant Results',
    'features.instant.desc': 'Get disease detection and remedies in seconds.',
    
    // Upload Page
    'upload.title': 'ফসলের ছবি আপলোড করুন',
    'upload.subtitle': 'Take a photo or upload an image of your crop for AI analysis',
    'upload.crop.label': 'ফসলের ধরন নির্বাচন করুন',
    'upload.crop.placeholder': 'আপনার ফসল বেছে নিন...',
    'upload.drop.text': 'Drop image here or click to upload',
    'upload.drop.formats': 'Supports: JPG, PNG (Max 5MB)',
    'upload.camera': 'Take Photo',
    'upload.gallery': 'Choose from Gallery',
    'upload.detect': 'রোগ নির্ণয় করুন',
    'upload.processing': 'Analyzing image...',
    'upload.error.invalidImage': 'কর করে একটি বৈধ ছবি নির্বাচন করুন',
    
    // Results
    'result.title': 'Detection Results',
    'result.crop': 'Crop',
    'result.disease': 'Detected Issue',
    'result.confidence': 'Confidence',
    'result.remedy.title': 'Recommended Treatment',
    'result.remedy.steps': 'Treatment Steps',
    'result.preventive': 'Preventive Measures',
    'result.share': 'Share Report',
    'result.share.whatsapp': 'Share on WhatsApp',
    'result.download': 'Download Report',
    'result.scan.again': 'Scan Another Crop',
    'chat.ask.assistant': 'Ask AI Assistant',
    'chat.placeholder': 'Type your farming question...',
    'chat.voice.start': 'Start voice input',
    'chat.voice.stop': 'Stop voice input',
    'chat.speak': 'Read aloud',
    'chat.stop.speaking': 'Stop reading',
    
    // About
    'about.title': 'AgroGuardian সম্পর্কে',
    'about.mission': 'Our Mission',
    'about.mission.text': 'Empowering farmers with AI-powered crop disease detection to improve agricultural productivity and food security.',
    'about.team': 'Our Team',
    'about.contact': 'Contact Us',
    'about.contact.form': 'Send us a message',
    'about.contact.name': 'Name',
    'about.contact.email': 'Email',
    'about.contact.message': 'Message',
    'about.contact.send': 'Send Message',
    
    // Admin
    'admin.title': 'Admin Dashboard',
    'admin.total.scans': 'Total Scans',
    'admin.diseases.detected': 'Diseases Detected',
    'admin.users.active': 'Active Users',
    'admin.accuracy': 'Detection Accuracy',
    'admin.recent.cases': 'Recent Cases',
    'admin.export': 'Export Data',
    'admin.crop': 'Crop',
    'admin.disease': 'Disease',
    'admin.date': 'Date',
    'admin.language': 'Language',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Something went wrong',
    'common.retry': 'Try Again',
    'common.success': 'Success!',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.close': 'Close',
    
    // Crops
    'crops.tomato': 'টমেটো',
    'crops.potato': 'আলু',
    'crops.wheat': 'গম',
    'crops.rice': 'চাল',
    'crops.corn': 'ভুট্টা',
    'crops.cotton': 'তুলা',
    'crops.sugarcane': 'আখ',
    'crops.soybean': 'সয়াবিন',
    
    // Footer
    'footer.brand': 'অ্যাগ্রোইন্ডিয়া',
    'footer.description': 'কৃষকদের AI-চালিত ফসল রোগ সনাক্তকরণের মাধ্যমে টেকসই কৃষির জন্য ক্ষমতায়ন।',
    'footer.quicklinks': 'দ্রুত লিঙ্ক',
    'footer.dashboard': 'ড্যাশবোর্ড',
    'footer.heatmap': 'হিটম্যাপ',
    'footer.copyright': '© ২০২৪ অ্যাগ্রোইন্ডিয়া. সর্বস্বত্ব সংরক্ষিত।',

    // HomePage
    'home.hero.smartFarming': 'স্মার্ট কৃষি',
    'home.hero.subtitle': 'AI-চালিত ফসল রোগ সনাক্তকরণের মাধ্যমে কৃষিতে বিপ্লব, টেকসই ভবিষ্যতের জন্য',
    'home.hero.cta': 'এখন পূর্বাভাস দিন',
    'home.how.title': 'কিভাবে কাজ করে',
    'home.how.subtitle': 'তিনটি সহজ ধাপে ফসল রোগ নির্ণয় পান',
    'home.steps.upload.title': 'আপলোড করুন',
    'home.steps.upload.desc': 'আপনার স্মার্টফোন ক্যামেরা দিয়ে ফসলের পাতার ছবি তুলুন',
    'home.steps.diagnose.title': 'রোগ নির্ণয়',
    'home.steps.diagnose.desc': 'আমাদের AI ছবিটি বিশ্লেষণ করে এবং সম্ভাব্য রোগ চিহ্নিত করে',
    'home.steps.remedies.title': 'চিকিৎসা পান',
    'home.steps.remedies.desc': 'বিস্তারিত চিকিৎসার সুপারিশ এবং প্রতিরোধমূলক টিপস পান',
    'home.sustainability.title': 'কেন টেকসই?',
    'home.sustainability.subtitle': 'স্মার্ট কৃষি ப்ரயுக்தியின் மூலம் சமுதாய வளிம்பு மற்றும் நீர்முகிய வளிம்பு முன்னேற்றம்',
    'home.sustainability.soil.title': 'மண் ஆரோக்கியம்',
    'home.sustainability.soil.desc': 'ஜைவிக முறைகள் மூலம் மண் வளத்தை மேம்படுத்துவது மற்றும் நீண்ட கால உற்பத்திக்கு முயற்சி மற்றும் நீர்முகிய வளிம்பு விவிவம் பராமரிக்கும் முறையாகும்.',
    'home.sustainability.cost.title': 'செலவு திறன்',
    'home.sustainability.cost.desc': 'இலக்கு வைத்த சிகிச்சைகள் மற்றும் ப்ரதிரோ஧மூலம் மூலம் செலவுகளை 40% குறைக்கவும்',
    'home.sustainability.yield.title': 'எதிர்கால விளைச்சல்',
    'home.sustainability.yield.desc': 'தரவு சார்ந்த அறிவுரைகளுடன் பயிர் விளைச்சலை 25% அதிகரிக்கவும்',
    'home.stats.accuracy': 'நிர்஭ুலத்தின் விகிதம்',
    'home.stats.diseases': 'சந்தித்த ரোগங்கள்',
    'home.stats.farmers': 'உதவிய குடியரசு',
    'home.stats.support': 'உதவி கிடைக்கிறது',
    'home.cta.title': 'உங்கள் விவசாயத்தை மாற்ற தயாரா?',
    'home.cta.subtitle': 'AgroIndia பயன்படுத்தும் ஆயிரக்கணக்கான குடியரசுகளுடன் சேருங்கள்.',
    'home.cta.button': 'உங்கள் யாத்திரியா தொடங்குங்கள்',
    // ResultPage
    'result.error.noResults': 'কোনও ফলাফল পাওয়া যায়নি',
    'result.error.uploadNew': 'নতুন ছবি আপলোড করুন',
    'result.backToUpload': 'আপলোডে ফিরে যান',
    'result.title': 'নির্ণয় ফলাফল',
    'result.reference.healthy': 'সুস্থ',
    'result.reference.early': 'প্রাথমিক স্তর',
    'result.reference.moderate': 'মাঝারি',
    'result.reference.severe': 'গুরুতর',
    'result.reference.guide': 'রোগ অগ্রগতি গাইড',
    'result.reference.desc': 'এই রেফারেন্স ছবিগুলি রোগের অগ্রগতিকে সুস্থ থেকে গুরুতর স্তরে দেখায়। উপসর্গ চিহ্নিত করতে এবং গুরুতরতা বুঝতে এগুলি ব্যবহার করুন।',
    'result.prevention.title': 'ভবিষ্যতের প্রতিরোধ টিপস',
    'result.share': 'ফলাফল শেয়ার করুন',
    'result.download': 'রিপোর্ট ডাউনলোড করুন',
    'result.askAssistant': 'AI সহকারীর কাছে জিজ্ঞাসা করুন',
    'result.scanAgain': 'আরেকটি ফসল স্ক্যান করুন',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};